import { Component, DestroyRef, effect, inject, input, signal, untracked } from '@angular/core';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';
import { RouterLink } from '@angular/router';
import { Subscription } from 'rxjs';
import { ApiError } from '../../core/http/api-error.model';
import { InvoicesService } from './invoices.service';

/**
 * The document's real PDF, generated by the backend itself — not a replica built in Angular and
 * printed through the browser. This page only fetches it and shows it: same file for everyone,
 * whatever they open it with.
 */
@Component({
  selector: 'app-invoice-print',
  imports: [RouterLink],
  templateUrl: './invoice-print.component.html',
  styleUrl: './invoice-print.component.css',
})
export class InvoicePrintComponent {
  private service = inject(InvoicesService);
  private sanitizer = inject(DomSanitizer);
  private destroyRef = inject(DestroyRef);

  /** From the route, through component input binding. */
  id = input.required<string>();

  loading = signal(false);
  pdfUrl = signal<SafeResourceUrl | null>(null);
  error = signal<string | null>(null);

  /** Kept alongside `pdfUrl` (a `SafeResourceUrl` can't be read back) to revoke it and to download it. */
  private blobUrl: string | null = null;
  private filename = 'document.pdf';

  private request?: Subscription;

  constructor() {
    effect(() => {
      const id = this.id();
      untracked(() => this.load(id));
    });

    this.destroyRef.onDestroy(() => this.revokeBlobUrl());
  }

  /** The blob URL already sits in the browser's cache: this only names the file for the user. */
  download(): void {
    const url = this.blobUrl;
    if (!url) return;

    const link = document.createElement('a');
    link.href = url;
    link.download = this.filename;
    link.click();
  }

  private load(id: string): void {
    this.request?.unsubscribe();
    this.revokeBlobUrl();
    this.pdfUrl.set(null);
    this.error.set(null);
    this.loading.set(true);

    this.request = this.service.getPdf(id).subscribe({
      next: ({ blob, filename }) => {
        this.loading.set(false);
        this.filename = filename;
        this.blobUrl = URL.createObjectURL(blob);
        this.pdfUrl.set(this.sanitizer.bypassSecurityTrustResourceUrl(this.blobUrl));
      },
      error: (error: ApiError) => {
        this.loading.set(false);
        this.error.set(error.message);
      },
    });
  }

  private revokeBlobUrl(): void {
    if (this.blobUrl) {
      URL.revokeObjectURL(this.blobUrl);
      this.blobUrl = null;
    }
  }
}
