import { Component, DestroyRef, effect, inject, input, signal, untracked } from '@angular/core';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';
import { RouterLink } from '@angular/router';
import { Subscription } from 'rxjs';
import { ApiError } from '../../core/http/api-error.model';
import { PurchaseOrdersService } from './purchase-orders.service';

/**
 * The order's real PDF ("Bon de commande"), generated by the backend itself — not a replica built
 * in Angular and printed through the browser. This page only fetches it and shows it: same file
 * for everyone, whatever they open it with. A draft's PDF carries no price, only articles and
 * quantities: the backend decides that from the order's status, not this page.
 */
@Component({
  selector: 'app-purchase-order-print',
  imports: [RouterLink],
  templateUrl: './purchase-order-print.component.html',
  styleUrl: './purchase-order-print.component.css',
})
export class PurchaseOrderPrintComponent {
  private service = inject(PurchaseOrdersService);
  private sanitizer = inject(DomSanitizer);
  private destroyRef = inject(DestroyRef);

  /** From the route, through component input binding. */
  id = input.required<string>();

  loading = signal(false);
  pdfUrl = signal<SafeResourceUrl | null>(null);
  error = signal<string | null>(null);

  /** Kept alongside `pdfUrl` (a `SafeResourceUrl` can't be read back) to revoke it and to download it. */
  private blobUrl: string | null = null;
  private filename = 'commande.pdf';

  private request?: Subscription;

  constructor() {
    effect(() => {
      const id = this.id();
      untracked(() => this.load(id));
    });

    this.destroyRef.onDestroy(() => this.revokeBlobUrl());
  }

  /** The blob URL already sits in the browser's cache: this only names the file for the user. */
  download(): void {
    const url = this.blobUrl;
    if (!url) return;

    const link = document.createElement('a');
    link.href = url;
    link.download = this.filename;
    link.click();
  }

  private load(id: string): void {
    this.request?.unsubscribe();
    this.revokeBlobUrl();
    this.pdfUrl.set(null);
    this.error.set(null);
    this.loading.set(true);

    this.request = this.service.getPdf(id).subscribe({
      next: ({ blob, filename }) => {
        this.loading.set(false);
        this.filename = filename;
        this.blobUrl = URL.createObjectURL(blob);
        this.pdfUrl.set(this.sanitizer.bypassSecurityTrustResourceUrl(this.blobUrl));
      },
      error: (error: ApiError) => {
        this.loading.set(false);
        this.error.set(error.message);
      },
    });
  }

  private revokeBlobUrl(): void {
    if (this.blobUrl) {
      URL.revokeObjectURL(this.blobUrl);
      this.blobUrl = null;
    }
  }
}
