import { Component, DestroyRef, effect, inject, input, signal, untracked } from '@angular/core';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';
import { RouterLink } from '@angular/router';
import { Subscription } from 'rxjs';
import { ApiError } from '../../core/http/api-error.model';
import { ReceptionsService } from './receptions.service';

/**
 * The reception's real PDF ("Bon de réception"), generated by the backend itself — not a replica
 * built in Angular and printed through the browser. Only this reception's own lines appear,
 * whatever else the order carries: a partial delivery gets its own bon to sign, not the order's
 * cumulative total. Same pattern as PurchaseOrderPrintComponent, for the order's own PDF.
 */
@Component({
  selector: 'app-reception-print',
  imports: [RouterLink],
  templateUrl: './reception-print.component.html',
  styleUrl: './reception-print.component.css',
})
export class ReceptionPrintComponent {
  private service = inject(ReceptionsService);
  private sanitizer = inject(DomSanitizer);
  private destroyRef = inject(DestroyRef);

  /** From the route, through component input binding. */
  id = input.required<string>();

  loading = signal(false);
  pdfUrl = signal<SafeResourceUrl | null>(null);
  error = signal<string | null>(null);

  /** For the "back to order" link: the route only carries the reception's own id. */
  purchaseOrderId = signal<string | null>(null);

  /** Kept alongside `pdfUrl` (a `SafeResourceUrl` can't be read back) to revoke it and to download it. */
  private blobUrl: string | null = null;
  private filename = 'bon-de-reception.pdf';

  private pdfRequest?: Subscription;
  private receptionRequest?: Subscription;

  constructor() {
    effect(() => {
      const id = this.id();
      untracked(() => this.load(id));
    });

    this.destroyRef.onDestroy(() => this.revokeBlobUrl());
  }

  /** The blob URL already sits in the browser's cache: this only names the file for the user. */
  download(): void {
    const url = this.blobUrl;
    if (!url) return;

    const link = document.createElement('a');
    link.href = url;
    link.download = this.filename;
    link.click();
  }

  private load(id: string): void {
    this.pdfRequest?.unsubscribe();
    this.receptionRequest?.unsubscribe();
    this.revokeBlobUrl();
    this.pdfUrl.set(null);
    this.purchaseOrderId.set(null);
    this.error.set(null);
    this.loading.set(true);

    this.pdfRequest = this.service.getPdf(id).subscribe({
      next: ({ blob, filename }) => {
        this.loading.set(false);
        this.filename = filename;
        this.blobUrl = URL.createObjectURL(blob);
        this.pdfUrl.set(this.sanitizer.bypassSecurityTrustResourceUrl(this.blobUrl));
      },
      error: (error: ApiError) => {
        this.loading.set(false);
        this.error.set(error.message);
      },
    });

    // Only needed for the back link: a failure here does not affect the PDF above.
    this.receptionRequest = this.service.getById(id).subscribe({
      next: reception => this.purchaseOrderId.set(reception.purchaseOrderId),
    });
  }

  private revokeBlobUrl(): void {
    if (this.blobUrl) {
      URL.revokeObjectURL(this.blobUrl);
      this.blobUrl = null;
    }
  }
}
