import { HttpClient } from '@angular/common/http';
import { Injectable, inject } from '@angular/core';
import { map } from 'rxjs';
import { PageResponse } from '../../core/models/page.model';
import { Reception, ReceptionCreateRequest, ReceptionLineRequest, ReceptionSummary } from '../../core/models/reception.model';
import { filenameFromContentDisposition } from '../invoices/invoice-format';

/** A file attached to a reception, with the filename the backend suggests for the download. */
export interface ReceptionFile {
  blob: Blob;
  filename: string;
}

/**
 * Calls to the backend ReceptionController. A reception is written as a draft, then confirmed:
 * only the confirmation moves the stock, and only a confirmed one can be cancelled. Confirming
 * is refused until the supplier invoice (number and file) has been attached.
 */
@Injectable({ providedIn: 'root' })
export class ReceptionsService {
  private http = inject(HttpClient);
  private url = '/api/v1';

  /** Newest first, 20 per page. Receptions only exist against an order. */
  getByOrder(orderId: string, page = 0) {
    return this.http.get<PageResponse<ReceptionSummary>>(`${this.url}/purchase-orders/${orderId}/receptions`, {
      params: { page },
    });
  }

  getById(id: string) {
    return this.http.get<Reception>(`${this.url}/receptions/${id}`);
  }

  /** Refused unless the order is waiting for its goods. */
  create(orderId: string, body: ReceptionCreateRequest) {
    return this.http.post<Reception>(`${this.url}/purchase-orders/${orderId}/receptions`, body);
  }

  addLine(receptionId: string, body: ReceptionLineRequest) {
    return this.http.post<Reception>(`${this.url}/receptions/${receptionId}/lines`, body);
  }

  removeLine(receptionId: string, lineId: string) {
    return this.http.delete<Reception>(`${this.url}/receptions/${receptionId}/lines/${lineId}`);
  }

  /** Draft only. Replaces whatever supplier invoice was attached before, if any. */
  setSupplierInvoice(receptionId: string, invoiceNumber: string, file: File) {
    const form = new FormData();
    form.set('invoiceNumber', invoiceNumber);
    form.set('file', file);
    return this.http.put<Reception>(`${this.url}/receptions/${receptionId}/supplier-invoice`, form);
  }

  downloadSupplierInvoice(receptionId: string) {
    return this.downloadFile(`${this.url}/receptions/${receptionId}/supplier-invoice/file`);
  }

  /** Any status but cancelled. Replaces whatever was uploaded before, if any. */
  uploadSignedReceipt(receptionId: string, file: File) {
    const form = new FormData();
    form.set('file', file);
    return this.http.post<Reception>(`${this.url}/receptions/${receptionId}/signed-receipt`, form);
  }

  downloadSignedReceipt(receptionId: string) {
    return this.downloadFile(`${this.url}/receptions/${receptionId}/signed-receipt/file`);
  }

  /** The reception's own real PDF ("Bon de réception"), generated by the backend — see purchase order's getPdf. */
  getPdf(receptionId: string) {
    return this.downloadFile(`${this.url}/receptions/${receptionId}/pdf`);
  }

  /** Moves the goods into the stock and advances the order. Refused with no line or no supplier invoice attached. */
  confirm(id: string) {
    return this.http.post<Reception>(`${this.url}/receptions/${id}/confirmation`, null);
  }

  /** Confirmed ones only: the stock movements are taken back. A draft is deleted instead. */
  cancel(id: string, reason: string) {
    return this.http.post<Reception>(`${this.url}/receptions/${id}/cancellation`, { reason });
  }

  deleteDraft(id: string) {
    return this.http.delete<void>(`${this.url}/receptions/${id}`);
  }

  private downloadFile(url: string) {
    return this.http.get(url, { responseType: 'blob', observe: 'response' }).pipe(
      map(
        (response): ReceptionFile => ({
          blob: response.body as Blob,
          filename: filenameFromContentDisposition(response.headers.get('Content-Disposition')) ?? 'document',
        }),
      ),
    );
  }
}
